// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xwuvluqtwkrpqcrajfmy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3dXZsdXF0d2tycHFjcmFqZm15Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2NjUyNjgsImV4cCI6MjA3MjI0MTI2OH0.4byYcKCbX4dBlguEXCDkgz-4EGWBMn1Vy2A0xuz-ucI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});